### ISSUE TITLE
Feature Request: Unique ID for sensor.samba_backup

### ISSUE THREAD

**Issue by BillyFKidney** [thomasmauerer/hassio-addons#102]
The Samba Backup does not have a unique ID, preventing the settings from being modified within the UI.
<img width="581" alt="image" src="https://user-images.githubusercontent.com/65253277/183523746-4986f05b-cea0-4009-98cd-72fbdf557728.png">

During installation if a unique ID is created additional configuration settings will become available, such as area:
<img width="393" alt="image" src="https://user-images.githubusercontent.com/65253277/183523576-5de55796-3b24-47be-9eb6-317c871f1110.png">

**Comment by thomasmauerer** [comment]
I don't think it is possible to add a unique id here. The sensor is different from others since there is no integration for it. The add-on simply posts the values via the Home Assistant API, which is - by the way - the reason why the sensor gets lost as soon as Home Assistant is restarted.

**Comment by BillyFKidney** [comment]
> I don't think it is possible to add a unique id here. The sensor is different from others since there is no integration for it. The add-on simply posts the values via the Home Assistant API, which is - by the way - the reason why the sensor gets lost as soon as Home Assistant is restarted.

Gotcha, I tried to setup a Sensor Template but that didn't go well. :(

I did follow your instructions on an automation to ensure the sensor is available. Thanks for that!
```
alias: Startup - Restore Samba Backup Sensor
description: >-
  There is a known limitation that the sensor will be unavailable if you restart
  Home Assistant. This is caused by the way Home Assistant handles sensors which
  are not backed up by an entity, but instead come from an add-on or AppDaemon.
trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id:
      - sensor.samba_backup
    attribute: state
    to: unavailable
condition: []
action:
  - service: hassio.addon_stdin
    data:
      addon: 15d21743_samba_backup
      input: restore-sensor
mode: single
```
