### ISSUE TITLE
Feature request: add keep days to manual backups

### ISSUE THREAD

**Issue by DrBlokmeister** [thomasmauerer/hassio-addons#114]
I run weekly and daily backups. The weekly backups I want to keep for a longer time than the daily backups to avoid using too much disk space while still having a few weeks of history. It would be nice to add the option keep_days to the manual backup service.

Proposed config:
```yaml
    - service: hassio.addon_stdin
      data:
        addon: 15d21743_samba_backup
        input:
          command: trigger
          keep_days: 30
          exclude: [a0d7b954_influxdb]
```
