### ISSUE TITLE
Manual trigger backup

### ISSUE THREAD

**Issue by N1c093** [thomasmauerer/hassio-addons#15]
Hello,
first of all, thank you for this great addon.

Is it currently possible to manual trigger an backup? I set the schedule inside the addon so it creates backup automatically.
```yaml
trigger_time: '03:00'
trigger_days:
  - Mon
  - Wed
  - Fri
  - Sun
```

I think the following service call gets disabled when you set a schedule inside the add on. Is it right?
```yaml
service: hassio.addon_stdin
data:
  addon: 15d21743_samba_backup
  input: trigger
```

It would be great to still have the possibility to create manual backups. For example before you install a new version of HA.

Thanks in advance.

**Comment by niro1987** [comment]
you can add ad many triggers as you'de like to an automation.

Set `trigger_time` to `manual` and add the following automation to run daily backups. This way you can run the automation manually or even post `trigger` to mqtt topic `samba_backup/status` for a manual backup (with a button card for example).


**automation.yaml**
```yaml
- id: sambabackup
  alias: Samba Backup
  description: ''
  trigger:
  - payload: trigger
    platform: mqtt
    topic: samba_backup/status
  - at: 00:00:00
    platform: time
  condition: []
  action:
  - data:
      addon: 15d21743_samba_backup
      input: trigger
    service: hassio.addon_stdin
```
