### ISSUE TITLE
Damaged backup file eash time so i cant open and would love to have a fix

### ISSUE THREAD

**Issue by IIIdefconIII** [thomasmauerer/hassio-addons#167]
Dear dev,

I was hoping to have this addon working correctly, the internal backup system works fine and i van open the homeassistant.tar.gz
But whenever i used this addon it does create the backup with the correct name + date + time, how i have set it up.
But when i then wanne open the homeassistant.,tar.gz in that file im always getting and error... I hope there is a easy fix for this.

This is the config, the orignal is not backup up with a password:
```
show_name: true
show_icon: true
type: button
entity: automation.smb_backup_now_2
tap_action:
  action: call-service
  service: hassio.addon_stdin
  data:
    addon: 15d21743_samba_backup
    input:
      command: trigger
      backup_name: Samba_Backup {date}
      backup_password: some_pwd
      exclude_addons:
        - core_mariadb
        - core_deconz
      exclude_folders:
        - ssl
  target: {}
name: Backup SMB Now
icon: mdi:cloud-upload-outline
```

![image](https://github.com/thomasmauerer/hassio-addons/assets/9917659/5655117a-1c79-4398-8f68-5ae494596233)
