### ISSUE TITLE
Question, Example Showing the Attributes in Entity card

### ISSUE THREAD

**Issue by coolje** [thomasmauerer/hassio-addons#186]
I managed alone to configure your extraordinary samba-backup to backup on my synology nas.
I am an beginner and my question might be not suitable for here.

I do fail in adding the attributes the sensor has (backups local, backups remote, total backups succeeded, total backups failed, last backup)  to an entity card.
In the example to show attributes in the entity-card it should be an syntax like:

type: entities
entities:
  - entity: sensor.samba_backup
  - entity: sensor.samba_backup
    attribute: backups local
    unit: "#"

but unfortunately this shows twice:

"Samba Backup    IDLE "          but unfortunately not the attribute backup local.
Do you have one small hint how to show this data on the entitie card or somehow else?

**Comment by morganfw** [comment]
Hi,
I managed the sensor configuration with the following code:

```
type: entities
entities:
  - entity: sensor.samba_backup
    icon: mdi:content-save
  - type: attribute
    entity: sensor.samba_backup
    attribute: total_backups_succeeded
    name: Total Backups Succeeded
    icon: mdi:check-circle
  - type: attribute
    entity: sensor.samba_backup
    attribute: total_backups_failed
    name: Total Backups Failed
    icon: mdi:close-circle
  - type: attribute
    entity: sensor.samba_backup
    attribute: last_backup
    name: Last Backup
    icon: mdi:clock-end
```

![image](https://github.com/user-attachments/assets/caa64c32-9052-435b-9e88-b70efbdc3982)

before configuring sensors and attributes, I configured Blueprint (or automation if you prefer) as reported in the documentation here: https://github.com/thomasmauerer/hassio-addons/blob/master/samba-backup/DOCS.md#home-assistant-sensor
