### ISSUE TITLE
Big changes ahead

### ISSUE THREAD

**Issue by tomlut** [thomasmauerer/hassio-addons#197]
While testing the 2025.1 beta release of home assistant core it has become clear that big changes are in the works for third party backup systems. Existing supervisor/add-on services will be replaced with targets/integrations available in Home Assistant. See:

https://developers.home-assistant.io/docs/core/platform/backup/

Additionally there is strong resistance from the developers to including an option to turn off encryption in any planned `backup.create` service. 

For now there is no indication of when the legacy methods will be depreciated so this is just an early heads up FYI.

**Comment by thomasmauerer** [comment]
Thanks for reporting.

Looks like that this add-on will soon come to an end. When I started this, Home Assistant itself did not provide much other than a service to create a backup. Things changed in the meantime and especially since 2023.06 and the possibility to mount a network storage, the need for this add-on has decreased already.

Since I'm still using this add-on myself everyday, I will try to keep it functioning as long as possible/needed. However, the future should definitely be an alternative solution implemented as a Home Assistant integration, not an add-on. Some things, e.g. the sensor handling is in fact just a hack, but there is no other possibility for add-ons. The correct way to do this has always been an integration.

Let's see... maybe I start working on a Samba integration if nobody else does it - once this is released and some more infos are available.

**Comment by tomlut** [comment]
Yeah an integration will be the way forward and I suspect it may be necessary. The home assistant developers always provide the _minimum_ viable functionality. No bells and whistles.

Either way, thank you for providing and supporting the add-on for all this time. It has provided much needed peace of mind and actual disaster recovery more than once - I really shouldn't beta test on my production system 😁

**Comment by den-mac** [comment]
So it seems like initial testing from others show that this might still work, as long as Thomas is calling the “Home Assistant Supervisor: Create a full backup” Service/Action.

https://community.home-assistant.io/t/3-2-1-backup/821341/49

**Comment by den-mac** [comment]
Also, from watching the Watch Party video it looks like there's a samba/NAS option built in for the destination for the backups. I'm mostly concerned about the encryption factor. Worst case I throw something together that makes the HASS call above and then rsyncs it to my NAS or something via a shell cron job or something.

**Comment by mucki12** [comment]
As @den-mac  mentioned, it might be great to implement Samba Backup with the action hassio.backup_full. Something tiny/easy:

```
actions:
  - action: hassio.backup_full
    metadata: {}
    data:
      compressed: true
      homeassistant_exclude_database: false
      location: SynoBackup
      name: >-
        Backup with no encryption {{
        state_attr('update.home_assistant_core_update','installed_version') }}
        {{ now().strftime('%Y-%m-%d') }}
```
