### ISSUE TITLE
Sensor are not working at Home Assistant start?

### ISSUE THREAD

**Issue by carsten-h** [thomasmauerer/hassio-addons#59]
Hello!

I am using this code in my ui-lovelace.yaml to show the Samba Backup sensors:
```
      - type: entities
        title: Samba Backup
        entities:
          - entity: sensor.samba_backup
            icon: mdi:file-replace-outline
            name: Backup Status
          - attribute: backups_local
            entity: sensor.samba_backup
            icon: mdi:file-outline
            name: Lokale Backups
            type: attribute
          - attribute: backups_remote
            entity: sensor.samba_backup
            icon: mdi:file-move-outline
            name: Remote Backups
            type: attribute
          - attribute: total_backups_succeeded
            entity: sensor.samba_backup
            icon: mdi:file-check-outline
            name: Erfolgreiche Backups
            type: attribute
          - attribute: total_backups_failed
            entity: sensor.samba_backup
            icon: mdi:file-cancel-outline
            name: Fehlgeschlagene Backups
            type: attribute
          - attribute: last_backup
            entity: sensor.samba_backup
            icon: mdi:file-clock-outline
            name: Letztes Backup
            type: attribute
        show_header_toggle: false

```

But after starting Home Assistant or starting Home Assistant Operating System these sensore are not available which is shown on my lovelace page.
When I restart Samba Backup they are available immediate.

What can be the problem here?
